import esbuild from 'esbuild'
import process from 'process'
import builtins from 'builtin-modules'
import esbuildSvelte from 'esbuild-svelte'
import { sveltePreprocess } from 'svelte-preprocess'
import { readFile } from 'fs/promises';
import { compileModule } from 'svelte/compiler';
import { transformSync } from 'esbuild';

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = (process.argv[2] === 'production')

const context = await esbuild.context({
	plugins: [
		esbuildSvelte({
			compilerOptions: { css: 'injected' },
			preprocess: sveltePreprocess(),
		}),
		// Add this plugin for .svelte.ts files
		{
			name: 'svelte-runes-modules',
			setup(build) {
				build.onLoad({ filter: /\.svelte\.(ts|js)$/ }, async (args) => {
					let source = await readFile(args.path, 'utf8');

					// Transform TypeScript to JavaScript first
					if (args.path.endsWith('.ts')) {
						const transformed = transformSync(source, {
							loader: 'ts',
							target: 'es2020'
						});
						source = transformed.code;
					}

					// Then compile with Svelte
					const result = compileModule(source, {
						filename: args.path,
						dev: build.initialOptions.minify !== true
					});

					return {
						contents: result.js.code,
						loader: 'js'
					};
				});
			}
		}
	],
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
})

if (prod) {
	await context.rebuild()
	process.exit(0)
} else {
	await context.watch()
}
